FROM python:3.9-slim

# Working Directory
WORKDIR /app

# Copy source code to working directory
COPY . /app

# Install packages from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Environment Variables
ENV ENV=production

# Run the main.py
CMD ["python", "main.py"]
